### PR TITLE
Major rework.

### PR DESCRIPTION
**Pull request by neveretth**
- Move student-edited code to student/ dir (which is ignored by .gitignore)
- Consolidate testing scripts to avoid unnecessary code
- Create Makefile to initialize labs
- Create test.sh to assist in running tests

----------------
There are a lot of changes here, talk to me on discord @neveretth.

In essence, it solves all the problems we saw in lab today.
- Git won't interfere
- Commands aren't confusing
- Easier to add labs

----------------
I've added a little bit to the README.md, but it *desperately* needs to be improved. Here's the tldr:
```bash
make <name-of-lab>
# creates a dir in student/<name-of-lab> with the *.cpp file
./test.sh <name-of-lab> 
# runs the testing suite
```

### CODE REVIEW

**Comment by seeker-3** [comment]
I appreciate you opening this PR.

This whole repo is a public-facing submodule of a private repo. All the content in this repo is autogenerated from scripts in the private-facing repo. Just on its face, these changes could not be accepted as they would interfere with the current way this repo is created from the private repo.

I don't see how this simplifies things because you're taking 1 step and making it 2. The current process is `git pull` and everything is ready. For yours, you do a pull, then you have to use your build tool and makefile. I'm not totally sure what you find confusing about the current way it is, it's just a Python script.

As for the multiple copies, again in the private repo, there is a "master copy" of the script that propagates through the repos if changes are made to it. The only downside to the multiple copies is the disk usage, and it's not that much. I prefer each folder kind of being its own context.

For the git conflicts, there is a script similar to your `filecheck.sh` in the private repo that checks if a directory already exists and doesn't copy it over to prevent conflicts, which again moves the complexity to our end instead of the student's.

The working tree being dirty is not really a problem since's student's aren't committing and pushing code. The only time `git status` is needed is usually to check if a student edited or created files by mistake.

> In essence, it solves all the problems we saw in lab today.

I don't really know what problems you are referring to. I used this repo for 3 semesters and never saw any of these problems.

What "problem" are you trying to solve exactly?

**Comment by seeker-3** [comment]
This PR could not be accepted because it would interfere with the build process in the private module.

**Comment by neveretth** [comment]
If the structure of this repo has worked for 3 previous semesters, then I agree it is best left as is. 

The "problems" I referenced were hopefully just growing pains as a result of having people inexperienced with git use it as part of their workflow. What happened was when running git pull, the `labname.cpp` files were overwritten (which shouldn't happen, but did?). Annoyingly, I cannot replicate this problem this morning, so perhaps it was something else that went wrong.

Either way, it's good to know this repo has a solid foundation. Hopefully everything sorts itself out in the coming weeks.

**Comment by seeker-3** [comment]
I talked to Ryan. It sounds like there was some confusion where people were creating the lab directories instead of pulling them which was creating conflicts. Hopefully, they can get this ironed out quickly.

I really appreciate you going the extra mile to do this! This looks like a decent amount of work and not something I would expect from a 102 student. Nice job!

**Pull request closed without merging**
